# The URL the site will be built for
base_url = "https://pyjamas.live"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

description = "pyjamasconf esta chegando"
title = "Pyjamas <br> Conf <br> 2019"

[extra]
links = [
    {url = "https://github.com/pyjamasconf/codigo-de-conduta", name = "Código de conduta"},
]
social = [
    {url = "https://twitter.com/pyjamasconf/", name = "Twitter"},
    {url = "https://t.me/pyjamasconf/", name = "Telegram"},
    {url = "https://github.com/pyjamasconf", name = "Github"},
    {url = "https://www.youtube.com/channel/UCWCFzEJd7PhVulMXwGjcYAA/", name = "Youtube"},
]
action_button = {url = "https://forms.gle/hXXJ8xM12tfFGvVm6", name= "Quero Palestrar!"}
date = "13-14 Dezembro 2019"
where = {url = "https://www.youtube.com/channel/UCWCFzEJd7PhVulMXwGjcYAA/", name="Youtube Live Stream"}
faqs = [
    {question = "Preciso me inscrever para assistir?", answer="Não é preciso se inscrever, é totalmente gratuíto e online! <br>Recomendamos que participe do grupo no <a href='http://t.me/pyjamasconf' target='_blank'>telegram</a> e acompanhe nas redes sociais para ficar sabendo quando divulgarmos a grade."},
    {question = "Quais serão os horários das transmissões", answer="Acontecerão entre 13/12/2019 16:00 até 14/12/2019 16:00, serão 24h de atividades online e em breve divulgaremos a grade e os links."},
    {question = "Sou iniciante, posso participar?", answer="Claro que sim! você pode inclusive ser palestrante, se tiver uma idéia para compartilhar preencha o formulário de submissão de proposta e faremos o possível para te auxiliar na sua transmissão."}
]
side_text = "PYJAMAS"
logo_medium = "/img/pyjamas_medium.png"


[extra.credits]
template = '<a href="https://colorlib.com" target="_blank">Colorlib</a>'
logo = '<a href="https://github.com/a-nelim" target="_blank">Milena Ferreira</a>'

[extra.contact]
title = "Pyjamas Org Team"
email = "pyjamasconf@gmail.com"
link = {url= "http://t.me/pyjamasconf", name="http://t.me/pyjamasconf"}

[extra.welcome]
title = "24h de #Python <br> diretamente do seu sofá <br> em Português e ao vivo!"
text = "O intuito é atingir Pythonistas espalhados por todo o mundo, nos mais variados fusos!"
link = {url="https://forms.gle/hXXJ8xM12tfFGvVm6", name="Você pode colaborar fazendo uma transmissão"}

[extra.program]
show = true
days = [
    {name="13 Dez 2019 <br> Sexta-feira", url="https://docs.google.com/spreadsheets/d/e/2PACX-1vQVEXTW1reD4YE_dt3hb3YKfAxI69JsWiQwjH3ZGXoR6qEIduURzXsw0wzRaNXinDbmEQQIKwDGSAWK/pubhtml?gid=1958679364&amp;single=true&amp;widget=false&amp;headers=false", style="width: 100%;height: 600px;"},
    {name="14 Dez 2019 <br> Sábado", url="https://docs.google.com/spreadsheets/d/e/2PACX-1vQVEXTW1reD4YE_dt3hb3YKfAxI69JsWiQwjH3ZGXoR6qEIduURzXsw0wzRaNXinDbmEQQIKwDGSAWK/pubhtml?gid=1013096590&amp;single=true&amp;widget=false&amp;headers=false", style="width: 100%;height: 600px;"}
]
